# Generated by Django 4.2.7 on 2023-12-01 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='N/A', max_length=30)),
                ('last_name', models.CharField(default='N/A', max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(default='N/A', max_length=15)),
                ('admin', models.BooleanField(default=False)),
                ('regular', models.BooleanField(default=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('recept_no', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(default='N/A', max_length=20)),
                ('borrower_id', models.CharField(default='N/A', max_length=20)),
                ('due_date', models.DateField(default='N/A')),
                ('return_date', models.DateField(default='N/A')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('title', models.CharField(default='N/A', max_length=100)),
                ('author', models.CharField(default='N/A', max_length=30)),
                ('isbn', models.CharField(default='N/A', max_length=20, unique=True)),
                ('genre', models.CharField(default='N/A', max_length=30)),
                ('category', models.CharField(default='N/A', max_length=30)),
                ('cover_photo', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('book_id', models.CharField(default='N/A', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('owner_id', models.CharField(default='N/A', max_length=20)),
                ('language', models.CharField(default='N/A', max_length=30)),
                ('condition', models.CharField(default='N/A', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
