# Generated by Django 4.2.7 on 2023-12-06 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no',
            field=models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
