# Generated by Django 4.2.7 on 2024-01-25 17:45

from django.db import migrations, models
import readventure.models


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_info',
            name='due_date',
            field=models.DateField(default=readventure.models.default_due_date),
        ),
    ]
