# Generated by Django 4.2.7 on 2023-12-06 22:17
# Generated by Django 4.2.7 on 2023-12-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
