# Generated by Django 4.2.7 on 2023-12-01 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0002_alter_books_book_id_alter_receipt_review_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklist', models.CharField(default='N/A', max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'booklist')},
            },
        ),
    ]
