# Generated by Django 4.2.7 on 2023-11-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='N/A', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='N/A', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='N/A', max_length=30, unique=True),
        ),
    ]
