# Generated by Django 4.2.7 on 2024-01-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0002_alter_exchange_info_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_info',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ignored', 'Ignored')], default='pending', max_length=10),
        ),
    ]
