# Generated by Django 4.2.7 on 2024-01-28 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0003_alter_exchange_info_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_info',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_book', to='readventure.books'),
        ),
        migrations.AlterField(
            model_name='exchange_info',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchange_info',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
