# Generated by Django 4.2.7 on 2023-12-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0003_alter_receipt_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
