# Generated by Django 4.2.7 on 2024-01-31 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0004_alter_exchange_info_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange_info',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchange_info',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
