# Generated by Django 4.2.7 on 2023-11-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
