# Generated by Django 4.2.7 on 2023-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0005_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='N/A', max_length=100)),
                ('author', models.CharField(default='N/A', max_length=30)),
                ('isbn', models.CharField(default='N/A', max_length=20, unique=True)),
                ('genre', models.CharField(default='N/A', max_length=30)),
                ('category', models.CharField(default='N/A', max_length=30)),
                ('cover_photo', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('book_id', models.CharField(default='N/A', max_length=20, unique=True)),
                ('owner_id', models.CharField(default='N/A', max_length=20)),
                ('language', models.CharField(default='N/A', max_length=30)),
                ('conditon', models.CharField(default='N/A', max_length=30)),
            ],
        ),
    ]
