# Generated by Django 4.2.7 on 2023-11-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0006_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept_no', models.CharField(default='N/A', max_length=20, unique=True)),
                ('book_id', models.CharField(default='N/A', max_length=20)),
                ('borrower_id', models.CharField(default='N/A', max_length=20)),
                ('due_date', models.DateField(default='N/A')),
                ('return_date', models.DateField(default='N/A')),
            ],
        ),
    ]
