# Generated by Django 4.2.7 on 2023-11-30 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0008_remove_books_book_id_remove_books_conditon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='cover_image',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
