# Generated by Django 4.2.7 on 2023-11-30 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readventure', '0009_rename_cover_image_books_cover_photo_books_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='regular',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='student_id'),
        ),
    ]
